runtime: go
api_version: go1.8

handlers:

- url: /push
  script: _go_app

- url: /temp
  script: _go_app

- url: /data
  script: _go_app

- url: /meta
  script: _go_app

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /datasize
  static_files: static/datasize.html
  upload: static/datasize.html

- url: /(.*\.(gif|png|jpg|html))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg|html)$